name: git push into another repo to deploy to vercel

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: List current directory
        run: ls -la

      - name: Check .storybook directory
        run: ls -la .storybook

      - name: creates output
        run: sh ./build.sh

      - name: Clear target repository
        run: |
          git clone https://github.com/JW-Ahn0/Meerket_Develop.git target_repo
          cd target_repo
          git rm -rf .
          git commit -m "Clear repository"
          git push origin main

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEVELOP_REPO_DEPLOYMENT_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: "JW-Ahn0"
          destination-repository-name: "Meerket_Develop"
          user-email: ${{ secrets.DEVELOP_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
